// Compile contracts/Monsocket.sol → src/lib/contract.ts (ABI + bytecode).
import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const source = readFileSync(new URL("../contracts/Monsocket.sol", import.meta.url), "utf8");
const input = {
  language: "Solidity",
  sources: { "Monsocket.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};
const out = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (out.errors ?? []).filter((e) => e.severity === "error");
if (errors.length) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}
const c = out.contracts["Monsocket.sol"].Monsocket;
writeFileSync(
  new URL("../src/lib/contract.ts", import.meta.url),
  `// generated by scripts/compile.mjs — do not edit\n` +
    `export const ABI = ${JSON.stringify(c.abi)} as const;\n` +
    `export const BYTECODE = "0x${c.evm.bytecode.object}" as const;\n`,
);
console.log("compiled → src/lib/contract.ts");
