// Deploy Monsocket to Monad testnet and record the address in
// src/lib/deployment.ts. Deployer key: PRIVATE_KEY env var, or a persisted
// throwaway at scripts/deployer-key.json (created on first run — fund it).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createPublicClient, createWalletClient, defineChain, formatEther, http } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const RPC = process.env.MONAD_RPC ?? "https://testnet-rpc.monad.xyz";
const chain = defineChain({
  id: 10143,
  name: "Monad Testnet",
  nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 },
  rpcUrls: { default: { http: [RPC] } },
});

const keyFile = new URL("./deployer-key.json", import.meta.url);
let pk = process.env.PRIVATE_KEY;
if (!pk) {
  if (!existsSync(keyFile)) writeFileSync(keyFile, JSON.stringify({ pk: generatePrivateKey() }));
  pk = JSON.parse(readFileSync(keyFile, "utf8")).pk;
}
const account = privateKeyToAccount(pk);
const pub = createPublicClient({ chain, transport: http(RPC) });
const balance = await pub.getBalance({ address: account.address });
console.log(`deployer ${account.address} — ${formatEther(balance)} MON`);
if (balance < 10n ** 17n) {
  console.error("fund the deployer with ≥0.1 testnet MON (https://faucet.monad.xyz), then rerun");
  process.exit(1);
}

const { ABI, BYTECODE } = await import("../src/lib/contract.ts");
const wallet = createWalletClient({ account, chain, transport: http(RPC) });
const hash = await wallet.deployContract({ abi: ABI, bytecode: BYTECODE });
console.log("deploy tx", hash);
const receipt = await pub.waitForTransactionReceipt({ hash });
console.log("Monsocket @", receipt.contractAddress, "block", receipt.blockNumber);
writeFileSync(
  new URL("../src/lib/deployment.ts", import.meta.url),
  `// generated by scripts/deploy.mjs — do not edit\n` +
    `export const CONTRACT = "${receipt.contractAddress}" as const;\n` +
    `export const RPC_URL = "${RPC}" as const;\n`,
);
console.log("recorded → src/lib/deployment.ts");
